quarkus.datasource.db-kind=oracle
quarkus.datasource.username=RM567630
quarkus.datasource.password=150101
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521/orcl
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.validate-in-dev-mode=false
quarkus.datasource.jdbc.driver=oracle.jdbc.OracleDriver
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=0
quarkus.swagger-ui.always-include=true
mp.openapi.extensions.smallrye.info.title=LinkAid API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API de gestão de contatos, tickets e painel de informações gerais.
